import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

import * as build from "../build/server";

import { getLoadContext } from "../app/load-context";

export const onRequest = createPagesFunctionHandler({
    // @ts-expect-error - the server build file is generated by `remix vite:build`
    build,
    // @ts-expect-error - don't know how to mock GetLoadContextFunction
    getLoadContext,
});
