import { createPagesFunctionHandler } from "@react-router/cloudflare";

import * as build from "../build/server";

import { getLoadContext } from "../app/load-context";

export const onRequest = createPagesFunctionHandler({
    // @ts-expect-error - the server build file is generated by `remix vite:build`
    build,
    getLoadContext,
});
