import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({
    // @ts-expect-error - the server build file is generated by `remix vite:build`
    build,
});
