ignore:
    - "*.config.js"
    - "*.config.ts"
    - "/packages/cli/scripts/**"

# Coverage checks shouldn't fail the build
coverage:
    status:
        project:
            default:
                target: 0%
        patch:
            default:
                target: 0%
