// Generated by Wrangler on Sun Aug 25 2024 12:37:55 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env-cf.d.ts`

interface CloudflareEnv {
	CF_BEARER_TOKEN: string;
	CF_ACCOUNT_ID: string;
	WEB_COUNTER_AE: AnalyticsEngineDataset;
}
