// Generated by Wrangler on Thu Jun 20 2024 16:14:46 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
    CF_BEARER_TOKEN: string;
    CF_ACCOUNT_ID: string;
    WEB_COUNTER_AE: AnalyticsEngineDataset;
}
