# default deploy name
name = "counterscale"
main = "./workers/app.ts"

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-12-13"

assets = { directory = "build/client" }

[[analytics_engine_datasets]]
  binding = "WEB_COUNTER_AE"
  dataset = "metricsDataset"