# default deploy name
name = "counterscale"
pages_build_output_dir = "build/client"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-12-13"

[[analytics_engine_datasets]]
  binding = "WEB_COUNTER_AE"
  dataset = "metricsDataset"