#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Prettify all files that are about to be committed
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

npx turbo test lint typecheck --concurrency=1

exit 0
